#生产
spring:
  datasource:
    url: jdbc:mysql://39.100.237.171:3306/massage?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1qaz!QAZ2wsx@WSX
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 20MB
      # 上传多个文件最大值,100Mb,默认10Mb
      max-request-size: 100MB
  redis:
    host: 39.100.237.171
    password: meili2020.
    timeout: 5000ms
    port: 6379
    database: 8
zfb-program:
  url: http://massage.1mmkj.com/massage/img/massageImg/
  image-upload-url: /webapp/integral/massage/img
  image-upload-path:
    prefix: /upload/clothingstore
    common: /app/
    factory: /app/factory/
    wholesaler: /app/wholesaler/
    commodity: /app/commodity/
    post: /app/post/
    post-comment: /app/post-comment/
    order-comment: /app/order-comment/
    recommend: /app/recommend/
    avatar: /app/avatar/
  app:
    redis:
      shop-prefix: shouwang_shop_
      home-page-init: shouwang_home_page_init
      hot-search: shouwang_shop_hot_search_commodities
      sort-page-init: shouwang_sort_page_init
      community-post-page-init: shouwang_community_post_page_init
server:
  port: 8082
massage:
  TcpService: 3456
  SERVICE_IP: 172.26.122.32